services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-server'
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    # environment:
    #   RABBITMQ_DEFAULT_USER: invent
    #   RABBITMQ_DEFAULT_PASS: 123456
    #   RABBITMQ_ERLANG_COOKIE: 'randomcookievalue'
    networks:
        - rabbitmq_go_net
    restart: unless-stopped
    labels:
      description: "RabbitMQ Server in container docker"
      maintainer: "manuelver"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  rabbitmq_go_net:
    driver: bridge
