services:
  tablamareas-app:
    build: .
    container_name: tablamareas-app
    depends_on:
      tablamareas-db:
        condition: service_healthy
      tablamareas-redis:
        condition: service_healthy
    networks:
      - tablamareas_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py || exit 1"]
      interval: 10s
      retries: 3
      start_period: 5s


  tablamareas-db:
    image: postgres:16-alpine
    container_name: tablamareas-db
    env_file:
      - .db.env
    networks:
      - tablamareas_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mareasuser -d tablamareasdb || exit 1"]
      interval: 10s
      retries: 3
      start_period: 5s


  tablamareas-redis:
    image: redis:alpine
    container_name: tablamareas-redis
    env_file:
      - .redis.env
    networks:
      - tablamareas_network
    restart: unless-stopped
    command: redis-server --requirepass "$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      start_period: 5s


networks:
  tablamareas_network:


volumes:
  pgdata:
