services:
  clima-app:
    build: .
    container_name: clima-app
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py || exit 1"]
      interval: 10s
      retries: 3
      start_period: 5s