services:
  clima-app:
    build: .
    container_name: clima-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py || exit 1"]
      interval: 10s
      retries: 3
      start_period: 5s